import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import ClientLayout from "./components/ClientLayout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DTAL",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const hideNavbarRoutes = ["/login", "/sign"];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#1b1c1d]`}
      >
       <ClientLayout>

        {children}
       </ClientLayout>
      </body>
    </html>
  );
}
